### PR TITLE
Fix #217

### LINKED ISSUE #217: Broken pipe error
when running `asdf install nodejs 14.15.4` I get this error:

```
/Users/lifeiscontent/.asdf/plugins/nodejs/bin/../lib/utils.sh: line 62: printf: write error: Broken pipe
```

### PR DESCRIPTION
**Pull request by lifeiscontent**

### CODE REVIEW

**Comment by lifeiscontent** [comment]
@Stratus3D any thoughts here?

**Comment by augustobmoura** [comment]
Yeah, this url change has nothing to do with the #217 issue, the broken pipe error is harmless but can confuse some users, it only occurs because we exit early in some points and bash3 printf doesn't handle broken pipes correctly, we might just ignore the error message with 2> /dev/null or find another way of tricking printf to not get the broken pipe signal, or ditching printf in favor of other printing method, maybe echo or calling the printf binary instead of the shell builtin.

@lifeiscontent are you still willing to fix #217?

I would go with the ignore path, listing versions is already slow because of new processes so no printf binary, and echo has some know problems with strings with -

**Comment by Stratus3D** [comment]
@augustobmoura yeah I knew this wasn't a fix for #217, but does the code itself look like an improvement?

**Comment by augustobmoura** [comment]
I mean, not really

Both the old and the new use a undocumented url from the Github website instead of the Github API and both redirect to codeload.github.com (which is the github releases CDN). The releases page link points to the /ref/tags url in the browser, but I think it pointed to the currently being used in asdf-nodejs in the past

I think the "most correct" URL would be from the api.github.com endpoint for tarballs that is actually [documented](https://docs.github.com/en/rest/reference/repos#download-a-repository-archive-tar), github probably will not shutdown the github.com endpoint because other repositories use it too, but is always good to use documented sources

**Comment by lifeiscontent** [comment]
@augustobmoura the original issue I had was due to not having gnupg installed. The pipe error was something I thought this would fix but it turns out that once I had gnupg installed everything worked correctly. The pipe error is a non issue for me. I do think a call out to having gnupg installed to use this plugin would be ideal though.

**Comment by augustobmoura** [comment]
I'm gonna close this PR for now, because it doesn't add that much to the project, I will give a look at using the api.github.com endpoint in another request though

**Pull request closed without merging**
