### PR TITLE
Fix path priority for global npm

### PR DESCRIPTION
**Pull request by smorimoto**
Fixes https://github.com/asdf-vm/asdf-nodejs/issues/56
Fixes https://github.com/asdf-vm/asdf-nodejs/issues/168 

This fixes the priority as follows:

Before

```
λ which --all npm
/home/smorimoto/.asdf/installs/nodejs/14.16.0/bin/npm
/home/smorimoto/.asdf/installs/nodejs/14.16.0/.npm/bin/npm
/home/smorimoto/.asdf/shims/npm

λ npm --version
6.14.11
```

After

```
λ which --all npm
/home/smorimoto/.asdf/installs/nodejs/14.16.0/.npm/bin/npm
/home/smorimoto/.asdf/installs/nodejs/14.16.0/bin/npm
/home/smorimoto/.asdf/shims/npm

λ npm --version
7.6.2
```

### CODE REVIEW

**Comment by smorimoto** [comment]
@vic @Stratus3D Could you check this?

**Comment by Stratus3D** [comment]
@augustobmoura @vadave can either of you or anyone else here test this out?

**Comment by smorimoto** [comment]
It's completely fixed, at least in my and my friend's environment, but it's very nice to check it in other environments as well.

**Comment by smorimoto** [comment]
You can check this as follows:

```
<switch branch>
asdf install nodejs 14.16.0
asdf shell nodejs 14.16.0
which npm
npm --version
npm install -g npm@latest
which npm
npm --version
```

**Comment by augustobmoura** [comment]
I'm taking a look at this, I kinda thought #168 was related with path ordering

@smorimoto can you send your friend's environment? Bash version, OS and interactive shell

Also I don't get it why your `which` command is showing the installs binaries, they shouldn't be in the path if I understood the asdf way of handling multiple versions correctly, only the shim version should be reachable and then it delegates execution to the installs binaries

**Comment by smorimoto** [comment]
The reason which shows such a result is that we use asdf-direnv to speed up asdf with a slightly tricky setup. However, this fixes the issues regardless of asdf-direnv.

**Comment by smorimoto** [comment]
If it's okay with my environment, I can share it right away:
OS: NixOS
Bash: 5.1.4
Fish: 3.2.0

**Comment by augustobmoura** [comment]
The problem seems to only occur with the direnv trick, I tested in the current master and it doesn't seems to have the problem. #168 should be another problem, probably related with the npm version and the npx executable, because I can't reproduce it anymore in the latest versions, I will give it more testing 

I will test the branch with the regular shim behavior against `npm`, `node` and `npx npm`, if it doesn't break anything and it helps with compatibility with direnv we might merge it

**Comment by augustobmoura** [comment]
Okay, can confirm that it works as expected, and it actually fixes #168 even for older npm versions (it was already fixed for npm >7, I guess `npx` now uses the same `npm` cli as itself?)

I think we can merge this @Stratus3D

**Comment by smorimoto** [comment]
@augustobmoura Thanks for confirm :)

**Comment by Stratus3D** [comment]
Thanks for the PR @smorimoto ! And thank you for testing this @augustobmoura ! Changes work for me as well. Sorry again for the late review.

**Review by Stratus3D — APPROVED** [review]

**Pull request merged**
