### PR TITLE
Export canonical npm prefix

### PR DESCRIPTION
**Pull request by charliegroll**
Addresses https://github.com/asdf-vm/asdf-nodejs/issues/157

### CODE REVIEW

**Comment by nowells** [comment]
I have run into this issue as well. Some tools (in my case, requireg) leverage the `rc` configuration of `prefix` to find where to require global modules from: https://github.com/h2non/requireg/blob/master/lib/resolvers.js#L81 this allows those types of use cases to still work!

**Comment by Stratus3D** [comment]
Is `npm_prefix` an environment variable? The docs I looked at seemed to indicate `prefix` was a command line flag.

**Comment by charliegroll** [comment]
@Stratus3D Yeah from [their docs](https://docs.npm.red/misc/config#environment-variables) every config flag can be used either way. I’ve tested my PR locally and it solves the issue for me.

**Comment by Stratus3D** [comment]
> @Stratus3D Yeah from [their docs](https://docs.npm.red/misc/config#environment-variables) every config flag can be used either way. I’ve tested my PR locally and it solves the issue for me.

Should this environment variable be named `npm_config_prefix` then?

**Comment by charliegroll** [comment]
@Stratus3D that's the one that already exists at https://github.com/asdf-vm/asdf-nodejs/pull/158/files#diff-e1d721568af624d970ad38a0165ecfb2R4 but that creates a `config_prefix` option instead of the `prefix` one. that might be a problem with npm, based on their documentation, but I can confirm this PR solves our problem by setting the `prefix` option

**Comment by Stratus3D** [comment]
I am confused because the documentation you linked to only mentioned `npm_config_prefix`. Is `npm_prefix` documented anywhere?

**Comment by charliegroll** [comment]
@Stratus3D that's a good point - it might be an issue with the dependency `requireg` has on https://github.com/dominictarr/rc

let me get back to you

**Comment by Stratus3D** [comment]
@charliegroll could it be that it is case sensitive? Maybe our existing code isn't working the way we think it is?

**Comment by augustobmoura** [comment]
Npm actually exports this variable when being executed, whats the point of we exporting it? In fact we exporting NPM_CONFIG_PREFIX at all is suspicious, npm already knows the current node installation dir by other means, mostly from introspection from the binary path. @charliegroll can you confirm if this is really needed?

**Pull request closed without merging**
