### PR TITLE
Fix broken install on MacOS

### PR DESCRIPTION
**Pull request by ZuraGuerra**
This PR implements @cdegroot 's fix, as stated in [here](https://github.com/asdf-vm/asdf-nodejs/issues/29#issuecomment-281734413).

It's still failling, though. Mind helping me find why? (I don't write much bash, normally...)

### CODE REVIEW

**Comment by cdegroot** [comment]
Don't have time to test today - what's the error you're getting? The diff looks good to me...

**Comment by urfolomeus** [comment]
This seems to be working for me installing NodeJS `7.4.0` on asdf version `0.2.0-dev` and Mac OX `10.12.3`.

```
» asdf install nodejs 7.4.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4566    0  4566    0     0  16695      0 --:--:-- --:--:-- --:--:-- 16664
gpg: Signature made Wed Jan  4 18:43:46 2017 GMT using RSA key ID 4C206CA9
gpg: Good signature from "Evan Lucas <evanlucas@me.com>" [unknown]
gpg:                 aka "Evan Lucas <evanlucas@keybase.io>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: B9AE 9905 FFD7 803F 2571  4661 B63B 535A 4C20 6CA9
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.7M  100 12.7M    0     0  2771k      0  0:00:04  0:00:04 --:--:-- 2771k
node-v7.4.0-darwin-x64.tar.gz: OK
```

**Comment by urfolomeus** [comment]
Checked out asdf `v0.2.1` and it still works for me. This time installing NodeJS `6.4.0` ...

```
» asdf install nodejs 6.4.0
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4467    0  4467    0     0   7598      0 --:--:-- --:--:-- --:--:--  7609
gpg: Signature made Tue Aug 16 15:47:49 2016 BST using RSA key ID DBE9B9C5
gpg: Good signature from "Colin Ihrig <cjihrig@gmail.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 94AE 3667 5C46 4D64 BAFA  68DD 7434 390B DBE9 B9C5
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 11.2M  100 11.2M    0     0   310k      0  0:00:36  0:00:36 --:--:--  256k
node-v6.4.0-darwin-x64.tar.gz: OK
```

**Comment by ZuraGuerra** [comment]
My bad, everyone!
I forgot the new signatures thing. It's working well! :)

**Comment by salimane** [comment]
@ZuraGuerra any update on the signatures thing ?

**Comment by samgranieri** [comment]
@salimane Here's how I managed to get installation of signed releases working in a project that has a .tool-versions file. 

FWIW, I already have GPG installed. 

```code
brew install gnupg2 coreutils 
asdf plugin-add asdf-nodejs https://github.com/ZuraGuerra/asdf-nodejs
gpg --keyserver pool.sks-keyservers.net --recv-keys 94AE36675C464D64BAFA68DD7434390BDBE9B9C5 FD3A5288F042B6850C66B31F09FE44734EB7990E 71DCFD284A79C3B38668286BC97EC7A07EDE3FC1 DD8F2338BAE7501E3DD5AC78C273792F7D83545D C4F0DFFF4E8C1A8236409D08E73BC641CC11F4C8 B9AE9905FFD7803F25714661B63B535A4C206CA9 56730D5401028683275BD23C23EFEFE93C4CFFFE
asdf install
```

**Comment by salimane** [comment]
@samgranieri  thanks for the workaround 👍

**Comment by ZuraGuerra** [comment]
Yep, it's exactly as @samgranieri said!

**Comment by HashNuke** [comment]
@ZuraGuerra Thanks for PR. Makes it easy.

What do you guys suggest about the failing build?

**Comment by HashNuke** [comment]
Merging the PR for now since this seems to be the agreed solution.

**Comment by HashNuke** [comment]
I've updated the readme to be a bit simpler for beginners with copy-paste instructions.

The main asdf readme now suggests installing `coreutils` for macOS.

**Comment by HashNuke** [comment]
Don't bother. Build fixed after merging this PR into master. Some issue with TravisCI

**Pull request merged**
