### PR TITLE
Switch to node-build 

### PR DESCRIPTION
**Pull request by neersighted**
This switches asdf-nodejs to use node-build as the backend. This fixes support for platforms that do not have binaries, and removes the somewhat problematic GPG verification code.

Instead, we rely on the hand-curated list of definitions that are maintained at the node-build repo. This also makes listing possible versions of node much faster, and introduces support for io.js (if anyone still needs it, I suppose) and other forks.

### CODE REVIEW

**Comment by Stratus3D** [comment]
Awesome! I'm going to test this out locally for a couple days before merging.

It looks like the build is failing due to a file being missing:

```
/home/travis/.travis/job_stages: line 57: ./bin/import-release-team-keyring: No such file or directory
```

Any idea what's wrong with it?

**Comment by mikemorris** [comment]
@Stratus3D Looks like this line just needs to be removed from the TravisCI config https://github.com/asdf-vm/asdf-nodejs/blob/84c111d2fc9b85e97bda6114e1735bf627bd0e2b/.travis.yml#L6

**Comment by neersighted** [comment]
I've rebased this so it can be considered again. I still strongly recommend node-build over using the official binaries as building from source is more compatible and standard with most other version managers.

**Comment by mikemorris** [comment]
https://github.com/nodenv/node-build is an underlying component of https://github.com/nodenv/nodenv, which _is_ far less used than the two leading Node.js version managers (https://github.com/creationix/nvm and https://github.com/tj/n), but I don't know if either of those have abstracted out support for building from Node.js versions from source.

Regardless, updating the GPG keyring and quirks around installing/building Node.js version have been a significant pain point for migrating from other version managers to asdf, and it would be nice to delegate this responsibility to a project with more active support.

**Comment by neersighted** [comment]
Sorry all for the lack of replies, it looks like this issue got filtered to junk mail thanks to the duplicate messages.

node-build is not an especially active project, but it is actively maintained and tested across many platforms. It works well, and thus it is not any more active than it needs to be.

I don't currently use asdf, but I think that switching to node-build represents a major improvement; it is significantly more ergonomic than dealing with a GPG keyring, and provides integrity guarantees through hashes in the upstream repo. You do have to trust node-build upstream, but you have to similarly trust that the `import-release-team-keyring` script in this repo is legitimate as well, so I don't see it as a strong regression.

I can fix the conflicts in this branch if there is interest, but I can't really test myself as I've switched back to `nodenv` on all my machines. Still, if someone else would like to take up the work of porting asdf-nodejs to node-build, I'd be happy to advise them.

**Comment by AlJohri** [comment]
Just wanted to point out that both `node-build` and `nodenv` seem to be up-to-date and maintained as of these days. Might be worth revisiting integration of `node-build` again. The GPG stuff is definitely a pain.

**Comment by quanganhtran** [comment]
I just recently installed asdf, and this is definitely a big obstacle to switching to it. For all the conveniences that asdf provides the adoption path is quite heavy with extra installations.

**Comment by Stratus3D** [comment]
It may be worth revisiting this. Ultimately this project is in need of more maintainers than anything else. As I don't use Node.JS on a daily basis I'm not the best person to make decisions like this.

**Pull request closed without merging**
